name: Angular CI

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Angular Full CI
      uses: colbyhill21/angular-full-ci@v1.0
      with:
        # Command to run tests on your project, do not prepend with "npm", it is already included.
        testcommand: run test
        # Set to true in order to run mocha tests. This option will install mocha on the image.
        mocha: false # optional
